In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
#from sklearn.svm import SVR
import numpy as np
#from sklearn.preprocessing import PolynomialFeatures

In [13]:
pairs = pd.read_csv('Pairs/training_data')

In [14]:
pairs.head()

Unnamed: 0  route_id     s     d  start_time  travel_time  weekday
0           0       1.0  13.0  14.0       537.0          3.0      0.0
1           3       1.0  14.0  16.0       729.0         12.0      0.0
2           4       1.0  12.0  13.0       491.0          4.0      0.0
3           5       1.0  12.0  14.0       491.0          8.0      0.0
4           6       1.0  12.0  15.0       491.0         12.0      0.0

In [15]:
pairs = pairs[['route_id','s','d','start_time','travel_time']]

In [16]:
pairs['start_time'] = pairs['start_time']/60

In [17]:
pairs['start_time'] = pairs['start_time'].map(lambda x : round(x,2))

In [18]:
pairs.head()

route_id     s     d  start_time  travel_time
0       1.0  13.0  14.0        8.95          3.0
1       1.0  14.0  16.0       12.15         12.0
2       1.0  12.0  13.0        8.18          4.0
3       1.0  12.0  14.0        8.18          8.0
4       1.0  12.0  15.0        8.18         12.0

In [49]:
#pairs=pairs.sort_values(['s','d'])

In [50]:
#pairs = pairs.astype('int')

In [51]:
#pairs.groupby(['s','d'])['travel_time'].mean()

In [19]:
model = LinearRegression()

In [53]:
#model = SVR()

In [20]:
#X = pairs[['s','d','start_time']]
X = pairs[['route_id','s','d','start_time']]

In [21]:
X = np.array(X)

In [37]:
X

array([[  1.  ,  13.  ,  14.  ,   8.95],
       [  1.  ,  14.  ,  16.  ,  12.15],
       [  1.  ,  12.  ,  13.  ,   8.18],
       ..., 
       [  1.  ,   3.  ,   2.  ,  20.22],
       [  1.  ,   3.  ,   1.  ,  20.22],
       [  1.  ,   2.  ,   1.  ,  20.3 ]])

In [23]:
y = pairs['travel_time']

In [24]:
y = np.array(y)

In [25]:
y.shape

(6947,)

In [26]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [27]:
model.predict([1,18,20,8.5])

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([ 42.7541659])

In [28]:
import pickle

In [30]:
pickle.dump(model,open('model','wb'))

In [32]:
model = pickle.load(open('model','rb'))

In [36]:
model.coef_

array([ 0.        ,  0.520709  ,  0.54698434, -1.06567688])